# Generated by Django 4.1.3 on 2022-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('title', models.CharField(help_text='Enter book title', max_length=20)),
                ('pubdate', models.DateTimeField(auto_now_add=True, help_text='Automatically applies time and date of creation')),
                ('book_file', models.FilePathField(help_text='Path to book file (needs testing)')),
            ],
            options={
                'ordering': ['title', '-pubdate'],
            },
        ),
    ]
