# Generated by Django 4.1.3 on 2022-11-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodelname',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mymodelname',
            name='my_field_name',
        ),
        migrations.AddField(
            model_name='mymodelname',
            name='uid',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
