# Generated by Django 4.1.3 on 2022-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_mymodelname_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='uid',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
