# Generated by Django 4.1.3 on 2022-11-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_author_book_bookinstance_genre_delete_books_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, choices=[('ru', 'Russian'), ('en', 'English'), ('fa', 'Farsi'), ('fr', 'French'), ('ua', 'Ukrainian')], default='ru', help_text='Book language', max_length=2)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.language'),
        ),
    ]
