# Generated by Django 4.1.3 on 2022-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_language_bookinstance_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language_name',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='Russian', help_text='Enter a book genre (e.g. Science Fiction)', max_length=200),
        ),
    ]
