# Generated by Django 4.1.3 on 2022-12-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
